version: '3.7'

services:
  django_gunicorn:
    build:
      context: .
    volumes:
      - static:/static
      - ./django_project:/app  # Mount local directory into the container
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  static:
  postgres_data:
